export const SET_IMAGES = 'SET_IMAGES';
export const SET_CATEGORIES = 'SET_CATEGORIES';
export const SET_FILETYPE = 'SET_FILETYPE';
export const SET_CURRENT_CATEGORY = 'SET_CURRENT_CATEGORY';
export const SET_NEXT_PAGE = 'SET_NEXT_PAGE';